name: talkenote
description: "A new Flutter project."

publish_to: "none"

version: 1.0.3+4

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.7.0
  flutter_native_splash: ^2.3.10

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  flutter_dotenv: ^5.0.2
  firebase_core: ^3.0.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.4
  record: ^5.1.0
  path_provider: ^2.1.2
  just_audio: ^0.9.38
  http: ^1.2.2
  uuid: ^4.5.1
  url_launcher: ^6.3.1

dependency_overrides:
  record_linux: ^1.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#61B8FF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

flutter_native_splash:
  android: true
  ios: true

  image: assets/images/splash.png
  color: "#A5F6A8"

  android_12:
    image: assets/images/splash.png
    icon_background_color: "#A5F6A8"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
    - assets/sounds/
    - .env
